---
abstract: unknown
author:
  - 'Steffen Ullrich <sullr.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-INET6Glue
no_index:
  directory:
    - t
    - inc
requires:
  IO::Socket::IP: '0.25'
  Net::FTP: '2.75'
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Queue=Net-INET6Glue
  homepage: https://github.com/noxxi/p5-net-inet6glue
  license: http://dev.perl.org/licenses/
  repository: https://github.com/noxxi/p5-net-inet6glue
version: '0.603'
